image: alpine:latest

before_script:
  - apk update
  - apk add python3 py3-pip git
  - pip3 install importlib-metadata

pages:
  stage: deploy
  script:
  - git clone --depth 1 https://gitlab.com/octtspacc/staticoso
  - mv staticoso/Source/* ./
  - python3 Build.py
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
