image: alpine:latest
pages:
  stage: deploy
  script: |
    export sitocttEnv=GitLab
    sh ./Scripts/Deploy.sh
  artifacts:
    paths:
      - build/public
  publish: build/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
