image: alpine:latest

pages:
  stage: deploy
  script: |
    sh ./Scripts/Requirements.sh
    sh ./Scripts/Produce.sh
  artifacts:
    paths:
      - build/public
  publish: build/public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
