image: alpine:latest

before_script:
  - apk update
  - apk add python3 py3-pip npm git
  - pip3 install Markdown
  - npm install -g pug-cli

pages:
  stage: deploy
  script:
  - git clone --depth 1 https://gitlab.com/octtspacc/staticoso
  - python3 staticoso/Source/Build.py
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

