image: alpine:latest

before_script:
  - apk update
  - apk add python3 npm git
  - npm install -g pug-cli

pages:
  stage: deploy
  script:
  - git clone --depth 1 https://gitlab.com/octtspacc/staticoso
  - Scripts/Deploy.GitLab.sh
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
