image: alpine:latest

before_script:
  - apk update
  - apk add python3 py3-pip npm go git
  - pip3 install requests lxml
  - npm install -g pug-cli

pages:
  stage: deploy
  script:
  - ./Scripts/Prepare.GitLab.html2gmi.sh
  - git clone --depth 1 https://gitlab.com/octtspacc/staticoso
  - ./Scripts/Deploy.GitLab.sh
  - ./Scripts/Deploy.Gemini.sh
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
