[[10-site]]
[10-site.title]
en = "About this site"
it = "Riguardo questo sito"

[[20-me]]
[20-me.title]
en = "Myself and my essence"
it = "Io e la mia essenza"

[[30-thanks]]
[30-thanks.title]
en = "Made thanks to"
it = "Fatto grazie a"

#[[40-spam]]
#[40-spam.title]
#en = "Interesting"
#it = "D'interesse"

[[50-fun]]
[50-fun.title]
en = "Other things"
it = "Altre cose"

#######################################

[[10-site]]
alt = "CC BY-SA"
file = "CC-BY-SA.svg"
href = "/miscellanea/Open-Source-sitoctt/"
#href = "https://creativecommons.org/licenses/by-sa/4.0/deed.it?ref=chooser-v1&title=%E2%9C%A8sitoctt%E2%9C%A8&href=https://sitoctt.octt.eu.org&creator=OctoSpacc"

[[10-site]]
alt = "✨sitoctt"
file = "Sites/sitoctt-1.png"
href = "/miscellanea/Raccolta-Siti-Internet/#il-mio"

[[10-site]]
alt = "Sign my guestoobk"
file = "Sign-guestbook.gif"
href = "https://listed.to/@u8/guestbook"

[[10-site]]
alt = "Warning: Page contains JavaScript!"
file = "Warning-Page-contains-JavaScript.png"

[[10-site]]
alt = "Best viewed with any browser"
file = "BEST-viewed-with-ANY-BROWSER.gif"

[[10-site]]
alt = "Mobile-Friendly"
file = "MOBILE-FRIENDLY.png"

[[10-site]]
alt = "This site is Miku-approved"
file = "this-site-is-MIKU-APPROVED.gif"

[[10-site]]
alt = "Not secure (HTTP) version"
file = "Not-secure-defcon1.gif"
href = "http://http.sitoctt.octt.eu.org"

[[10-site]]
alt = "Download Offline Version"
file = "OFF-LINE-VERSION.png"
href = "/miscellanea/Copie-sitoctt/#archivi-offline"

[[10-site]]
alt = "Written by Human, not by AI"
file = "written-by-human-not-by-ai-white.svg"
href = "https://notbyai.fyi"

#######################################

[[20-me]]
alt = "Follow me on Mastodon"
file = "Follow-me-on-mastodon.png"
href = "https://mastodon.uno/@octo"
rel = "me"

[[20-me]]
alt = "Visita la OctoSpacc Hub"
file = "Sites/octospacc-hub-1.png"
href = "https://hub.octt.eu.org"
rel = "me"

[[20-me]]
alt = "Visita il mio Fritto Misto di OctoSpacc"
file = "Sites/fritto-misto-di-octospacc-1.png"
href = "https://octospacc.altervista.org"
rel = "me"

[[20-me]]
alt = "Bandiera Octt"
file = "Octt-Flag.png"

[[20-me]]
alt = "Rainbow"
file = "rainbow_bev.png"
href = "https://en.wikipedia.org/wiki/Refraction"
spam = true

# Source: https://astral.town | License: Unknown
[[20-me]]
alt = "Occhi blink blink"
src = "@/Media/Blink-0.gif"

[[20-me]]
alt = "I wear cute socks!"
file = "I-wear-cute-socks.gif"

[[20-me]]
alt = "nya~"
file = "nya.png"

[[20-me]]
alt = "Hello Kitty"
file = "HELLO-Kitty.gif"
href = "https://www.sanrio.com"
spam = true

[[20-me]]
alt = "Girl rot"
file = "GRL-ROT.gif"

[[20-me]]
alt = "Cyber rot"
file = "CYBER-ROT.gif"

[[20-me]]
alt = "Girls for Notepad"
file = "girls-4-notepad.gif"

[[20-me]]
alt = "Perfect Soldier"
file = "Perfect-Soldier.gif"

[[20-me]]
alt = "I like computer"
file = "I-LIKE-COMPUTER.png"

#######################################

[[30-thanks]]
alt = "Made with Hugo"
file = "HUGO.webp"
href = "https://gohugo.io"
spam = true

[[30-thanks]]
alt = "Made with CSS"
file = "MADE-WITH-CASCADING-STYLE-SHEETS-cyan.png"
href = "https://developer.mozilla.org/en-US/docs/Web/CSS"
spam = true

[[30-thanks]]
alt = "Made on GNU/Linux"
file = "Made-on-GNU-Linux.png"
href = "https://www.gnu.org/home.it"
spam = true

[[30-thanks]]
alt = "Made with Notepad++"
file = "Made-with-Notepad++.png"
href = "https://notepad-plus-plus.org"
spam = true

[[30-thanks]]
alt = "Made with Microsoft Notepad"
file = "Powered-by-Microsoft-Notepad.gif"

[[30-thanks]]
alt = "Graphics by GIMP"
file = "Graphics-by-Gimp.png"
href = "https://www.gimp.org"
spam = true

[[30-thanks]]
alt = "Fueled by Coffee"
file = "Fueled-by-COFFEE.gif"

[[30-thanks]]
alt = "Powered by THE VOID"
file = "Powered-by-THE-VOID.png"

[[30-thanks]]
alt = "Powered by Bob"
file = "POWERED-BY-bob.gif"

#######################################

[[50-fun]]
alt = "Internet Archive"
file = "Sites/Internet-Archive.png"
href = "https://archive.org"
spam = true

[[50-fun]]
alt = "Wikipedia"
file = "Sites/Wikipedia.png"
href = "https://www.wikipedia.org"
title = "hu:User:Boro, CC BY-SA 3.0 &lt;https://creativecommons.org/licenses/by-sa/3.0&gt;, via Wikimedia Commons"
linkback = "https://commons.wikimedia.org/wiki/File:Wikipedia-microbar-hu.png"
spam = true

[[50-fun]]
alt = "Firefox"
file = "Firefox-Modern.png"
href = "https://www.mozilla.org/it/firefox"
spam = true

[[50-fun]]
alt = "The Onion Router"
file = "Tor.png"
href = "https://www.torproject.org/it"
spam = true

[[50-fun]]
alt = "uBlock Origin Now!"
file = "uBlock-Origin-Now.png"
href = "https://ublockorigin.com"
spam = true

# Linux Now badge with Xenia the Linux Fox made by Volt: https://meow.social/@voltbun/109600348286574222
[[50-fun]]
alt = "Linux Now!"
file = "Linux-NOW-Xenia.png"
href = "https://kernel.org"
spam = true

[[50-fun]]
alt = "Use Linux Online"
file = "Linux-Online.png"
href = "https://www.onworks.net"
spam = true

[[50-fun]]
alt = "Haiku OS Now!"
file = "HAIKU-NOW.png"
href = "https://www.haiku-os.org"
spam = true

[[50-fun]]
alt = "Join the Fediverse!!!"
file = "Join-the-Fediverse.gif"
href = "https://jointhefediverse.net"
spam = true

[[50-fun]]
alt = "matrix"
file = "matrix.png"
href = "https://matrix.org"
spam = true

[[50-fun]]
alt = "VOCALOID Now!"
file = "VOCALOID-Now.png"
href = "https://www.vocaloid.com"
spam = true

#######################################

[[60-fun]]
alt = "ISO 8601 now!"
file = "ISO-8601-now.png"
href = "https://www.w3.org/QA/Tips/iso-date"
spam = true

[[60-fun]]
alt = "I support net neutrality"
file = "I-SUPPORT-NET-NEUTRALITY.png"
href = "https://en.wikipedia.org/wiki/Net_neutrality"
spam = true

[[60-fun]]
alt = "I support right to repair"
file = "I-SUPPORT-RIGHT-TO-REPAIR.png"
href = "https://en.wikipedia.org/wiki/Right_to_repair"
spam = true

[[60-fun]]
alt = "Trans Your Gender"
file = "TRANS-YOUR-GENDER.gif"

[[60-fun]]
alt = "Ban Porn"
file = "BAN-PORN.png"

[[60-fun]]
alt = "Defective by Design"
file = "DEFECTIVE-by-design-ELIMINATE-DRM-NOW.webp"
href = "https://www.defectivebydesign.org"
spam = true

[[60-fun]]
alt = "Illegal number"
file = "aacs.2925462440.png"
href = "https://en.wikipedia.org/wiki/Illegal_number"
spam = true

[[60-fun]]
alt = "Piracy Now!"
file = "Piracy-Now.png"
href = "https://fmhy.pages.dev"
spam = true

[[60-fun]]
alt = "Sharing is caring, seed your torrents"
file = "Sharing-is-caring-seed-your-torrents.gif"

# “Emulate Now!” badge from Neon with a Zero on Tumblr: https://ne0nwithazero.tumblr.com/post/702936474323206144
[[60-fun]]
alt = "Emulate Now!"
file = "Emulate-Now.png"
href = "https://rentry.org/emulation"
spam = true

[[60-fun]]
alt = "Campaign against iFrames!"
file = "Campaign-against-FRAMES.gif"

