[[site]]
alt = "CC BY-SA"
file = "CC-BY-SA.svg"
href = "https://creativecommons.org/licenses/by-sa/4.0/deed.it?ref=chooser-v1&title=%E2%9C%A8sitoctt%E2%9C%A8&href=https://sitoctt.octt.eu.org&creator=OctoSpacc"

[[site]]
alt = "✨sitoctt"
file = "Sites/sitoctt-1.png"
href = "/it/miscellanea/Raccolta-Siti-Internet/#il-mio"

[[site]]
alt = "Warning: Page contains JavaScript!"
file = "Warning-Page-contains-JavaScript.png"

[[site]]
alt = "Best viewed with any browser"
file = "BEST-viewed-with-ANY-BROWSER.gif"

[[site]]
alt = "Mobile-Friendly"
file = "MOBILE-FRIENDLY.png"

[[site]]
alt = "This site is Miku-approved"
file = "this-site-is-MIKU-APPROVED.gif"

[[site]]
alt = "Not secure (HTTP) version"
file = "Not-secure-defcon1.gif"
href = "http://http.sitoctt.octt.eu.org"

[[site]]
alt = "Download Offline Version"
file = "OFF-LINE-VERSION.png"
href = "https://github.com/octospacc/sitoctt/archive/refs/heads/gh-pages.zip"

