name: Build and Deploy with staticoso

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  page_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt update
        sudo apt install -y npm python3.10 curl git
        curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3.10
        sudo pip3 install lxml
        sudo npm install -g pug-cli
        sh ./Scripts/Get.staticosoDevFixed.sh
        sh ./Scripts/Deploy.GitHub.sh

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public
