name: Build and Deploy
on:
  push:
    branches: [ "sitoctt-next" ]
  pull_request:
    branches: [ "sitoctt-next" ]
jobs:
  page_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: |
        export sitocttEnv=GitHub
        sh ./Scripts/Deploy.sh
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
